[DATASET]
dataset_package = decentralizepy.datasets.text.Twitter
dataset_class = Twitter
model_class = BERT
tokenizer = BERT
train_dir = /datasets/sent140/train
test_dir = /datasets/sent140/test
; python list of fractions below
sizes =
random_seed = 90
test_batch_size = 256
at_most = None

[OPTIMIZER_PARAMS]
optimizer_package = torch.optim
optimizer_class = SGD
lr = 0.005

[TRAIN_PARAMS]
training_package = decentralizepy.training.text.LLMTraining
training_class = LLMTraining
rounds = 1
full_epochs = True
batch_size = 32
shuffle = True
loss_package = torch.nn
loss_class = CrossEntropyLoss


[NODE]
graph_degree = 4

[SHARING]
sharing_package = decentralizepy.sharing.SharingAsymmetric
sharing_class = SharingAsymmetric
save_models_for_attacks = 100
save_all_models=False
nb_models_to_save=10

[COMMUNICATION]
comm_package = decentralizepy.communication.TCP
comm_class = TCP
addresses_filepath = /ip.json